steps:
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["clean","install","-DskipTests"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/gcloud", "--build-arg=JAR_FILE=initiate-payments-0.0.1-SNAPSHOT.jar", "."]
images: ["gcr.io/$PROJECT_ID/gcloud"]
